### ISSUE TITLE
Disable multiselect

### ISSUE THREAD

**Issue by lintz18** [ambek/XRM.Multiselect#2]
Hello,

I try to block the fields of the multiselect,  in my crm i need to disable all the fields because depend on the selection of one field.

My problem is that using javascript i've got to block all fields but, the multiselect no.

You know about a method to disable the booleans and can't click in?

Thanks!

![image](https://user-images.githubusercontent.com/24481932/38073255-85b877d0-332a-11e8-886c-d273ec650fc4.png)

And this is my javascript:

function setFieldDisabled() {
	var optionset = Xrm.Page.getAttribute("abs_tipodecuenta").getValue();
	if (optionset == null)
	{
		Xrm.Page.getAttribute("abs_tipodecuenta").setValue(100000000);
		Xrm.Page.getControl("abs_tipodecuenta").setDisabled(true);
	}
        if (Xrm.Page.getAttribute("abs_tipodecuenta").getText() == 'Clientes' ||
    	    Xrm.Page.getAttribute("abs_tipodecuenta").getText() == 'Agencias' ||
    	    Xrm.Page.getAttribute("abs_tipodecuenta").getText() == 'Distribuidores') 
        {
               disableFormFields();
        } 
        else {
              enableFormFields();
              Xrm.Page.getControl("abs_tipodecuenta").setDisabled(true);
    }
}

 function disableFormFields()
{
       Xrm.Page.ui.controls.forEach(function (control, index) {
           var controlType = control.getControlType();
           if (controlType != 'iframe' && controlType != 'webresource' && controlType != 'subgrid')
           {
               control.setDisabled(true);
           }
       });
}

 function enableFormFields()
{
       Xrm.Page.ui.controls.forEach(function (control, index) {
           var controlType = control.getControlType();
           if (controlType != 'iframe' && controlType != 'webresource' && controlType != 'subgrid')
           {
               control.setDisabled(false);
           }
       });
}

**Comment by ryanmaclean365** [comment]
Hi @lintz18 ,

I added the ability to disable the multiselect fields, see https://github.com/ryannipper/XRM.Multiselect

Ryan

**Comment by ambek** [comment]
I updated style text-decoration: line-through; 
Let me know how do you like it.
